Repository paw-ong/final-pawong-backend, pull requests merged in 2025-05, with the labels that each got.

#11 Openai chat completion model 환경변수로 관리
  src/main/resources/application.yml
Labels: 🔨 Refactor

#14 [PW-5] 마이페이지 "작성한 실종 게시글 목록" api 구현
  src/main/java/kr/co/pawong/pwbe/global/config/ClockConfig.java
  src/main/java/kr/co/pawong/pwbe/global/util/TimeUtils.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostPostDataCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostPostDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/entity/GeoPointEmbeddable.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/repository/LostPostJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/user/UserInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostPostDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostPostCard.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostPostDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/UserInfoPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataService.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/AuthController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/MyPageController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/UserController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/request/SignUpRequest.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/response/BaseMyPageResponse.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/response/UserResponse.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/dto/KakaoUserResponse.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/UserDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/entity/UserEntity.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/lostPost/LostPostInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/AuthUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/CommandUserDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryMyPageDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryNicknameUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryUserDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/AuthResponse.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/MyPageLostPostResponse.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/UserCreate.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/UserUpdate.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/mapper/MyPageMapper.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/LostPostInfoPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/UserDataCommandPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/UserDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/dto/MyPageLostPostInfo.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/mapper/LostPostMapper.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryMyPageDataService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryUserDataService.java
  src/test/java/kr/co/pawong/pwbe/global/util/TimeUtilsTest.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapperTest.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataServiceTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/port/in/mapper/MyPageMapperTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/port/out/mapper/LostPostMapperTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/service/QueryMyPageDataServiceTest.java
Labels: ✨ Feature

#17 [PW-12] 실종동물 상세보기 api 구현
  src/main/java/kr/co/pawong/pwbe/global/error/errorcode/CustomErrorCode.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/LostPostQueryController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostAdoptionDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostPostDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/entity/LostAdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/repository/LostAdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/shelter/ShelterCareNmAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostAdoptionDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostPostDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostAdoptionDetailDto.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostAdoptionDetailResponse.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostPostDetailDto.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostPostDetailResponse.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostAdoptionDetailMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostDetailMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostAdoptionDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostPostDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/ShelterCareNmPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/domain/LostAdoption.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/port/in/QueryCareNmUseCase.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/QueryShelterDataService.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/filter/JwtFilter.java
  src/main/java/kr/co/pawong/pwbe/user/config/SecurityConfig.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#19 [PW-2] 스프링 배치 구현
  build.gradle
  src/main/java/kr/co/pawong/pwbe/PawongBackendApplication.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/api/AdoptionCommandController.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/AdoptionJobScheduler.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionAiProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionApiProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionEsProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionAiReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionApiReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionEsReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionAiWriter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionApiWriter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionEsWriter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/es/EsAdoptionEngineCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/JpaAdoptionDataCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/JpaAdoptionDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/entity/AdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/repository/AdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/ApiRequestUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/CommandAdoptionDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/CommandAdoptionEngineUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/QueryAdoptionDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/dto/AdoptionCreate.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/out/AdoptionDataCommandPort.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/out/AdoptionDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/ApiRequestService.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/CommandAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/CommandAdoptionEngineService.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/QueryAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/adoption/domain/model/Adoption.java
  src/main/java/kr/co/pawong/pwbe/adoption/enums/ActiveState.java
  src/main/java/kr/co/pawong/pwbe/global/config/AdoptionBatchConfig.java
  src/main/java/kr/co/pawong/pwbe/global/config/RestTemplateConfig.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/api/ApiRequestService.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/ApiShelterService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#24 [PW-22] 게시글 수정 및 삭제 API
  src/main/java/kr/co/pawong/pwbe/global/error/errorcode/CustomErrorCode.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/LostPostCommandController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/dto/request/LostPostCreateRequest.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/dto/request/LostPostUpdateRequest.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostPostDataCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/entity/LostPostEntity.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/repository/LostPostJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/CommandLostPostDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostPostDataCommandPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/CommandLostPostDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/domain/LostPost.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/filter/JwtFilter.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/service/CommandLostPostDataServiceTest.java
Labels: ✨ Feature

#18 [PW-7] 이미지 업로드 시 S3 presign url을 생성해서 전달
  build.gradle
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/adapter/in/S3ImageController.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/adapter/in/dto/request/PresignUrlRequest.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/adapter/in/dto/response/PresignUrlResponse.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/adapter/out/S3Config.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/adapter/out/S3ImageStorageAdapter.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/application/port/in/ImageStorageUseCase.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/application/port/out/ImageStoragePort.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/application/service/S3ImageStorageService.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/s3/util/StorageUtil.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature

#26 [PW-21] shelter에 없는 보호소 정보 adoption에서 가져와 DB에 저장 로직 구현
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionApiProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionApiReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionApiWriter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/JpaAdoptionDataCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/shelter/ShelterCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/ApiAdoptionUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/CommandAdoptionDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/out/ShelterCommandPort.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/out/dto/AdoptionCareDto.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/CommandAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/adoption/domain/model/Adoption.java
  src/main/java/kr/co/pawong/pwbe/global/config/AdoptionBatchConfig.java
  src/main/java/kr/co/pawong/pwbe/global/util/ApiDataUtils.java
  src/main/java/kr/co/pawong/pwbe/global/util/TimeUtils.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/api/ApiAdoptionService.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/api/ApiShelterService.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/api/dto/AdoptionCreate.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/api/dto/ShelterCreate.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostDetailMapper.java
  src/main/java/kr/co/pawong/pwbe/shelter/adapter/in/api/ShelterUpdateController.java
  src/main/java/kr/co/pawong/pwbe/shelter/adapter/out/persistence/jpa/JpaShelterDataCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/shelter/adapter/out/persistence/jpa/JpaShelterDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/shelter/adapter/out/persistence/jpa/repository/ShelterJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/port/in/UpdateShelterDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/port/out/ShelterDataCommandPort.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/port/out/ShelterDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/UpdateShelterDataService.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/support/ShelterMapper.java
  src/main/java/kr/co/pawong/pwbe/shelter/domain/Shelter.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#23 [PW-15] 실종동물 북마크 및 북마크 조회 api 구현
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/FavoritesController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/user/BookmarkInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/user/UserInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostAnimalDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostPostDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostAnimalQuery.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/BookmarkInfoPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostAnimalDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataService.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/LostBookmarkController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/MyPageController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/response/BookmarkResponse.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/JpaLostBookmarkCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/JpaLostBookmarkQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/entity/LostBookmarkEntity.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/repository/LostBookmarkRepository.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/lostPost/LostPostInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/lostPost/mapper/LostAnimalQueryMapper.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryBookmarkDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryMyPageDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/ToggleBookmarkUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/MyPageLostPostResponse.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/mapper/MyPageMapper.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/LostBookmarkCommandPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/LostBookmarkQueryPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/LostPostInfoPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/dto/MyPageLostPostInfo.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/mapper/LostPostMapper.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryBookmarkDataService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryMyPageDataService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/ToggleBookmarkService.java
  src/main/java/kr/co/pawong/pwbe/user/domain/LostBookmark.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapperTest.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataServiceTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/port/in/mapper/MyPageMapperTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/service/QueryMyPageDataServiceTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/service/ToggleBookmarkServiceTest.java
  src/test/java/kr/co/pawong/pwbe/user/domain/LostBookmarkTest.java
Labels: ✨ Feature

#28 [PW-27] 로그 파일 추가
  src/main/java/kr/co/pawong/pwbe/global/filter/TracingFilter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/LostBookmarkController.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/config/ai.yml
  src/main/resources/config/security.yml
  src/main/resources/logback-spring.xml
  src/test/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapperTest.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataServiceTest.java
  src/test/java/kr/co/pawong/pwbe/user/application/service/QueryMyPageDataServiceTest.java
Labels: ✨ Feature

#33 [PW-31] 배치 & 추천리스트 코드 수정
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/AdoptionJobScheduler.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/JpaAdoptionDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/repository/AdoptionJpaRepository.java
Labels: 🔨 Refactor

#29 [PW-20] 실종동물 검색, 목록 api 구현
  .gitignore
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/QueryAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/LostAdoptionQueryController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/LostPostQueryController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/LostPostSearchController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/dto/request/LostPostSearchRequest.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/dto/response/LostAdoptionDetailResponse.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/dto/response/LostPostDetailResponse.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostAdoptionDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/JpaLostPostDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/entity/LostAdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/query/LostPostQueryBuilder.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/repository/LostPostJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostAdoptionDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/QueryLostPostDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/SearchLostPostDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostPostCard.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostPostDetailDto.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostPostSearchResponses.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/SliceLostPostSearchResponses.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostDetailMapper.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostAdoptionDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostPostDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostAnimalDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/SearchLostPostDataService.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostPostCardMapperTest.java
Labels: ✨ Feature

#39 [PW-38] Kafka 설정
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/kr/co/pawong/pwbe/global/config/KafkaTopicConfig.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/messaging/adapter/out/KafkaMessagePublisher.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/messaging/application/port/in/PublishMessageUseCase.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/messaging/application/port/out/MessagePublishPort.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/messaging/application/service/PublishMessageService.java
  src/main/java/kr/co/pawong/pwbe/test/adapter/in/api/TestController.java
  src/main/java/kr/co/pawong/pwbe/test/adapter/in/api/dto/TestMessagePublishDto.java
  src/main/java/kr/co/pawong/pwbe/test/adapter/in/messaging/kafka/KafkaTestConsumer.java
  src/main/java/kr/co/pawong/pwbe/test/adapter/in/messaging/kafka/dto/TestMessageConsumeDto.java
  src/main/java/kr/co/pawong/pwbe/test/application/port/in/PrintLogUseCase.java
  src/main/java/kr/co/pawong/pwbe/test/application/service/PrintLogService.java
  src/main/resources/application.yml
  src/main/resources/config/kafka.yml
Labels: ✨ Feature

#32 [PW-25] 찜 기능 리팩토링
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/in/QueryAdoptionDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/QueryAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/FavoritesService.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/FavoritesServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/dto/FavoritesRequest.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/port/FavoritesRepository.java
  src/main/java/kr/co/pawong/pwbe/favorites/infrastructure/entity/FavoritesEntity.java
  src/main/java/kr/co/pawong/pwbe/favorites/infrastructure/entity/repository/FavoritesJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/favorites/infrastructure/entity/repository/FavoritesRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/FavoritesController.java
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/dto/response/FavoritesListResponse.java
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/dto/response/FavoritesResponse.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/AuthController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/FavoritesController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/LostBookmarkController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/MyPageController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/UserController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/response/FavoritesResponse.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/adoption/AdoptionInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/JpaFavoritesCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/JpaFavoritesQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/JpaLostBookmarkQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/UserDataCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/UserDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/entity/FavoritesEntity.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/entity/LostBookmarkEntity.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/repository/FavoritesJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/repository/LostBookmarkRepository.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/repository/UserJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/CustomOAuth2User.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/CustomOAuth2UserService.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/CustomUserDetails.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/CustomUserDetailsService.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/JwtTokenProvider.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/error/exception/FilterAuthenticationException.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/filter/JwtFilter.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/AuthUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryFavoritesDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryMyPageDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/ToggleFavoritesUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/MyPageFavoritesResponse.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/AdoptionInfoPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/FavoritesCommandPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/FavoritesQueryPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/AuthService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryFavoritesDataService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryMyPageDataService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryUserDataService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/ToggleFavoritesService.java
  src/main/java/kr/co/pawong/pwbe/user/config/SecurityConfig.java
  src/main/java/kr/co/pawong/pwbe/user/config/WebClientConfig.java
  src/main/java/kr/co/pawong/pwbe/user/domain/Favorites.java
  src/main/java/kr/co/pawong/pwbe/user/domain/User.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#58 [PW-57] 입양 추천리스트 & FCM 토큰 저장 수정
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/JpaAdoptionDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/repository/AdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/fcm/application/service/FcmService.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/fcm/domain/FcmToken.java
Labels: 🔨 Refactor

#65 [PW-62] Firebase 관련 환경변수 secrets로 관리 및 FcmConfig 변경
  .github/workflows/cicd.yml
  src/main/java/kr/co/pawong/pwbe/global/config/FcmConfig.java
Labels: 🐞 BugFix

#73 [PW-72] 채팅메세지 DTO에 메세지 전송자의 프로필 이미지 정보 추가
  src/main/java/kr/co/pawong/pwbe/chat/application/listener/ChatMessageEventListener.java
  src/main/java/kr/co/pawong/pwbe/chat/application/port/in/dto/ChatMessageDetail.java
  src/main/java/kr/co/pawong/pwbe/chat/application/service/QueryChatMessageDataService.java
Labels: 🐞 BugFix

#71 [PW-54] 유기동물 이미지를 받아오기 위한 프록시 사용
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/proxy/ProxyUrlAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/port/out/ProxyUrlPort.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/QueryAdoptionDataService.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/SearchAdoptionEngineService.java
  src/main/java/kr/co/pawong/pwbe/adoption/domain/model/Adoption.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/proxy/wsrv/application/port/in/ProxyUrlUseCase.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/proxy/wsrv/application/service/WsrvProxyUrlService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 💻 CrossBrowsing, ✨ Feature
