Repository paw-ong/final-pawong-backend, pull requests merged in 2025-06, with the labels that each got.

#69 [PW-60] 유사 동물 SSE로 전달
  build.gradle
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/es/query/AdoptionQueryBuilder.java
  src/main/java/kr/co/pawong/pwbe/global/config/KafkaConsumerConfig.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/api/LostAnimalQueryController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/sse/LostAnimalStreamController.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/sse/LostPostIndexedEventListener.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/sse/SseEmitters.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/in/sse/event/LostPostIndexedEvent.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/messaging/LostAnimalMessagePublisher.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/es/document/LostAnimalDocument.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/es/query/LostAnimalQueryBuilder.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/SearchSimilarLostAnimalsUseCase.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/SearchSimilarLostAnimalsService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/StreamSimilarAnimalsService.java
  src/main/resources/application-local.yml
  src/main/resources/config/kafka.yml
Labels: ✨ Feature

#64 [PW-40] 회원가입시 이메일 인증 구현 (Redis 추가)
  build.gradle
  docker-compose.yml
  src/main/java/kr/co/pawong/pwbe/global/config/EmailConfig.java
  src/main/java/kr/co/pawong/pwbe/global/config/RedisConfig.java
  src/main/java/kr/co/pawong/pwbe/global/error/errorcode/CustomErrorCode.java
  src/main/java/kr/co/pawong/pwbe/global/util/CodeGenerator.java
  src/main/java/kr/co/pawong/pwbe/global/util/RedisUtils.java
  src/main/java/kr/co/pawong/pwbe/notification/application/port/in/CustomMailSenderUseCase.java
  src/main/java/kr/co/pawong/pwbe/notification/application/port/in/MailUseCase.java
  src/main/java/kr/co/pawong/pwbe/notification/application/service/CustomMailSenderService.java
  src/main/java/kr/co/pawong/pwbe/notification/application/service/MailService.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/EmailController.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/request/EmailVerificationRequest.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/in/api/dto/request/SignUpRequest.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/UserDataQueryAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/entity/UserEntity.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/jpa/repository/UserJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/user/adapter/out/security/filter/JwtFilter.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/AuthUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/QueryUserDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/in/dto/UserUpdate.java
  src/main/java/kr/co/pawong/pwbe/user/application/port/out/UserDataQueryPort.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/AuthService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/QueryUserDataService.java
  src/main/java/kr/co/pawong/pwbe/user/config/SecurityConfig.java
  src/main/java/kr/co/pawong/pwbe/user/domain/User.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/config/mail.yml
  src/main/resources/templates/codemail.html
  src/test/java/kr/co/pawong/pwbe/global/util/RedisUtilsTest.java
  src/test/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostPostDataServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#79 [PW-78] Kafka 토픽 변경
  src/main/java/kr/co/pawong/pwbe/global/config/KafkaTopicConfig.java
  src/main/java/kr/co/pawong/pwbe/notification/adapter/in/messaging/KafkaMessageConsumer.java
  src/main/java/kr/co/pawong/pwbe/notification/application/service/NotificationService.java
  src/main/resources/config/kafka.yml
Labels: 🔨 Refactor

#83 [PW-81] 채팅방의 비활성화 및 연결된 LostPost 정보를 받아오는 API
  src/main/java/kr/co/pawong/pwbe/chat/adapter/in/api/ChatRoomQueryController.java
  src/main/java/kr/co/pawong/pwbe/chat/adapter/in/api/dto/response/ChatRoomResponse.java
  src/main/java/kr/co/pawong/pwbe/chat/adapter/in/api/dto/response/ChatRoomStatusResponse.java
  src/main/java/kr/co/pawong/pwbe/chat/adapter/out/persistence/jpa/repository/ChatRoomJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/chat/application/port/in/QueryChatRoomDataUseCase.java
  src/main/java/kr/co/pawong/pwbe/chat/application/service/QueryChatRoomDataService.java
Labels: ✨ Feature

#87 [PW-86] 배치 파일 삭제
  build.gradle
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/AdoptionJobScheduler.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionAiProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionApiProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/processor/AdoptionEsProcessor.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionAiReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionApiReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/reader/AdoptionEsReader.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionAiWriter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionApiWriter.java
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/in/batch/writer/AdoptionEsWriter.java
  src/main/java/kr/co/pawong/pwbe/global/config/AdoptionBatchConfig.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#85 [PW-84] fcm 토큰 업데이트 구현
  src/main/java/kr/co/pawong/pwbe/infrastructure/fcm/application/service/FcmService.java
  src/main/java/kr/co/pawong/pwbe/infrastructure/fcm/domain/FcmToken.java
Labels: 🔨 Refactor

#70 [PW-63] 모니터링 설정
  .gitignore
  docker-compose.yml
  infra/monitoring/prometheus/prometheus.yml
  infra/monitoring/promtail/promtail.yml
  infra/nginx/conf/default.conf
Labels: ✨ Feature

#99 [PW-98] `@SQLRestriction` 어노테이션 추가
  src/main/java/kr/co/pawong/pwbe/adoption/adapter/out/persistence/jpa/entity/AdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/jpa/entity/LostAdoptionEntity.java
Labels: 🔨 Refactor

#105 [PW-104] postId 추가
  src/main/java/kr/co/pawong/pwbe/chat/application/listener/ChatNotificationListener.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/notification/NotificationSendAdapter.java
  src/main/java/kr/co/pawong/pwbe/notification/adapter/out/persistence/jpa/NotificationAdapter.java
  src/main/java/kr/co/pawong/pwbe/notification/adapter/out/persistence/jpa/entity/NotificationEntity.java
  src/main/java/kr/co/pawong/pwbe/notification/application/port/in/dto/NotificationRequest.java
  src/main/java/kr/co/pawong/pwbe/notification/application/service/NotificationService.java
  src/main/java/kr/co/pawong/pwbe/notification/application/service/dto/NotificationDto.java
  src/main/java/kr/co/pawong/pwbe/notification/domain/Notification.java
Labels: 🔨 Refactor

#107 [PW-106] ES에 있지만, RDB에 없을 경우 ES에서 해당 데이터 삭제
  src/main/java/kr/co/pawong/pwbe/global/error/errorcode/CustomErrorCode.java
  src/main/java/kr/co/pawong/pwbe/lostPost/adapter/out/persistence/es/EsLostAnimalEngineCommandAdapter.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/out/LostAnimalEngineCommandPort.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/IndexLostAnimalService.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/service/QueryLostAnimalDataService.java
Labels: 🐞 BugFix

#115 [PW-113] LostAdoptionDetailDto에 특징을 tagsField로 수정
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/dto/LostAdoptionDetailDto.java
  src/main/java/kr/co/pawong/pwbe/lostPost/application/port/in/mapper/LostAdoptionDetailMapper.java
  src/main/resources/templates/similarAdoptionMail.html
Labels: 🔨 Refactor
